name: Socialxmatch
description: Demonstrates how to use the health plugin.
publish_to: "none"
version: 4.5.0

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  permission_handler: ^10.2.0
  matrix: ^0.20.2
  provider: ^6.0.5
  path_provider: ^2.0.15
  tflite_flutter: ^0.10.1
  olm: ^2.0.3
  flutter_inappwebview: ^5.7.2+3
  app_usage: ^2.1.1
  geolocator: ^9.0.2
  geocoding: ^2.1.0
  on_audio_query: ^2.9.0
  google_sign_in: ^6.1.4
  googleapis: ^11.2.0
  dart_openai: 1.9.7
  shared_preferences: ^2.1.0
  url_launcher: ^6.1.10
  flutter_chat_ui: 1.6.6
  sqflite: ^2.2.8+4
  google_ml_kit: ^0.15.0
  get: ^4.6.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  health:
    

flutter:
  uses-material-design: true

  assets:
 
    - assets//model.tflite

