List<String> eventKeywords = [
  'football'
      'match',
  'basketball'
      'tournament',
  'tennis',
  'championship',
  'golf',
  'outing',
  'swimming competition',
  'baseball game',
  'cricket tournament',
  'rugby match',
  'hockey game',
  'volleyball league',
  'skiing trip',
  'snowboarding event',
  'surfing competition',
  'cycling race',
  'running marathon',
  'triathlon event',
  'boxing match',
  'martial arts tournament',
  'fitness bootcamp',
  'yoga retreat',
  'dance workshop',
  'zumba class',
  'pilates session',
  'rock climbing expedition',
  'hiking trip',
  'adventure race',
  'kayaking excursion',
  'sailing regatta',
  'paintball competition',
  'eSports tournament',
  'gaming convention',
  'cosplay event',
  'comic book convention',
  'anime expo',
  'music concert',
  'live performance',
  'DJ party',
  'karaoke night',
  'jam session',
  'classical music recital',
  'opera performance',
  'ballet show',
  'stand-up comedy',
  'improv night',
  'magic show',
  'circus performance',
  'theater play',
  'musical',
  'film screening',
  'movie premiere',
  'film festival',
  'art exhibition',
  'gallery opening',
  'photography showcase',
  'sculpture exhibition',
  'fashion show',
  'design expo',
  'craft fair',
  'food festival',
  'wine tasting',
  'beer festival',
  'culinary competition',
  'farmers market',
  'cooking workshop',
  'baking class',
  'wine and cheese pairing',
  'charity fundraiser',
  'benefit concert',
  'silent auction',
  'community fair',
  'fundraising gala',
  'blood donation drive',
  'volunteer event',
  'academic conference',
  'workshop',
  'seminar',
  'lecture series',
  'research symposium',
  'career fair',
  'technology summit',
  'hackathon',
  'startup pitch competition',
  'innovation expo',
  'business networking',
  'leadership seminar',
  'motivational speaker event',
  'educational webinar',
  'writing workshop',
  'book reading',
  'literary festival',
  'poetry slam',
  'science exhibition',
  'astronomy stargazing',
  'environmental summit',
  'climate change conference',
  'health and wellness expo',
  'medical conference',
  'mental health workshop',
  'fitness challenge',
  'yoga retreat',
  'meditation workshop',
  'nutrition seminar',
  'art therapy session',
  'spiritual retreat',
  'personal development seminar',
  'travel and adventure expo',
  'outdoor camping trip',
  'wildlife safari',
  'cultural festival',
  'music festival',
  'heritage celebration',
  'street fair',
  'parade',
  'fireworks display',
  'carnival',
  'theme park visit',
  'beach party',
  'BBQ cookout',
  'picnic in the park',
  'family fun day',
  'children\'s festival',
  'pet adoption event',
  'dog show',
  'pet-friendly gathering',
  'car show',
  'motorcycle rally',
  'auto racing event',
  'art and craft workshop',
  'DIY project class',
  'gardening workshop',
  'home improvement expo',
  'furniture exhibition',
  'fashion market',
  'jewelry showcase',
  'pop-up shop',
  'vintage flea market',
  'technology fair',
  'gaming tournament',
  'robotics exhibition',
  'virtual reality experience',
  'comic book signing',
  'collectibles fair',
  'board game night',
  'birthday party',
  'wedding',
  'conference',
  'music concert',
  'sports event',
  'art exhibition',
  'movie premiere',
  'book launch',
  'charity fundraiser',
  'business seminar',
  'fashion show',
  'food festival',
  'gala dinner',
  'trade show',
  'product launch',
  'workshop',
  'hackathon',
  'job fair',
  'comedy show',
  'theater performance',
  'academic conference',
  'technology summit',
  'networking event',
  'wine tasting',
  'cultural festival',
  'awards ceremony',
  'dance competition',
  'yoga retreat',
  'car show',
  'craft fair',
  'farmers market',
  'wellness retreat',
  'marathon',
  'gaming tournament',
  'beer festival',
  'art auction',
  'community fair',
  'science exhibition',
  'music festival',
  'beauty pageant',
  'cooking class',
  'coding bootcamp',
  'fundraising gala',
  'outdoor adventure',
  'youth camp',
  'painting workshop',
  'fitness challenge',
  'film screening',
  'job training',
  'healthcare summit',
  'photography exhibition',
  'environmental conference',
  'startup pitch competition',
  'virtual reality experience',
  'culinary competition',
  'entrepreneurship workshop',
  'music workshop',
  'design conference',
  'poetry reading',
  'hiking excursion',
  'dog show',
  'baking competition',
  'charity run',
  'art therapy session',
  'language exchange meetup',
  'motivational seminar',
  'farm-to-table dinner',
  'football match',
  'basketball tournament',
  'tennis championship',
  'golf outing',
  'swimming competition',
  'baseball game',
  'cricket tournament',
  'rugby match',
  'hockey game',
  'volleyball league',
  'skiing trip',
  'snowboarding event',
  'surfing competition',
  'cycling race',
  'running marathon',
  'triathlon event',
  'boxing match',
  'martial arts tournament',
  'fitness bootcamp',
  'yoga retreat',
  'dance workshop',
  'zumba class',
  'pilates session',
  'rock climbing expedition',
  'hiking trip',
  'adventure race',
  'kayaking excursion',
  'sailing regatta',
  'paintball competition',
  'eSports tournament',
  'gaming convention',
  'cosplay event',
  'comic book convention',
  'anime expo',
  'music concert',
  'live performance',
  'DJ party',
  'karaoke night',
  'jam session',
  'classical music recital',
  'opera performance',
  'ballet show',
  'stand-up comedy',
  'improv night',
  'magic show',
  'circus performance',
  'theater play',
  'musical',
  'film screening',
  'movie premiere',
  'film festival',
  'art exhibition',
  'gallery opening',
  'photography showcase',
  'sculpture exhibition',
  'fashion show',
  'design expo',
  'craft fair',
  'food festival',
  'wine tasting',
  'beer festival',
  'culinary competition',
  'farmers market',
  'cooking workshop',
  'baking class',
  'wine and cheese pairing',
  'charity fundraiser',
  'benefit concert',
  'silent auction',
  'community fair',
  'fundraising gala',
  'blood donation drive',
  'volunteer event',
  'academic conference',
  'workshop',
  'seminar',
  'lecture series',
  'research symposium',
  'career fair',
  'technology summit',
  'hackathon',
  'startup pitch competition',
  'innovation expo',
  'business networking',
  'leadership seminar',
  'motivational speaker event',
  'educational webinar',
  'writing workshop',
  'book reading',
  'literary festival',
  'poetry slam',
  'science exhibition',
  'astronomy stargazing',
  'environmental summit',
  'climate change conference',
  'health and wellness expo',
  'medical conference',
  'mental health workshop',
  'fitness challenge',
  'yoga retreat',
  'meditation workshop',
  'nutrition seminar',
  'art therapy session',
  'spiritual retreat',
  'personal development seminar',
  'travel and adventure expo',
  'outdoor camping trip',
  'wildlife safari',
  'cultural festival',
  'music festival',
  'heritage celebration',
  'street fair',
  'parade',
  'fireworks display',
  'carnival',
  'theme park visit',
  'football',
  'sports',
  'conference',
  'hackathon',
  'science fair',
  'competition',
  'tournament',
  'spelling bee',
  'quiz bowl',
  'debate',
  'poetry',
  'open mic',
  'comedy',
  'dance recital',
  'opera concert',
  'symphony',
  'art auction',
  'workshop',
  'class',
  'calligraphy',
  'origami',
  'floral arrangement',
  'wine and painting',
  'culinary',
  'cooking class',
  'chocolate tasting',
  'beer brewing',
  'mixology',
  'charity run',
  'cycling tour',
  'agility',
  'equestrian',
  'archery',
  'golf',
  'tennis',
  'skydiving',
  'hot air balloon',
  'sailing',
  'surfing',
  'scuba diving',
  'paddleboarding',
  'yoga',
  'wellness',
  'mindfulness',
  'nutrition',
  'self-defense',
  'language learning',
  'photography',
  'birdwatching',
  'cleanup',
  'sustainability',
  'coding',
  'app development',
  'data science',
  'virtual reality',
  'startup',
  'business',
  'marketing',
  'leadership',
  'finance',
  'TED talk',
  'writing retreat',
  'book club',
  'literary',
  'author signing',
  'art history',
  'poetry workshop',
  'science fiction',
  'archaeology',
  'photography exhibition',
  'wildlife conservation',
  'astronomy',
  'space exploration',
  'mental health',
  'fitness',
  'running',
  'marathon',
  'nutrition',
  'yoga retreat',
  'wellness expo',
  'dance fitness',
  'hiking',
  'triathlon',
  'watersports',
  'team building',
  'language exchange',
  'cultural',
  'cooking demonstration',
  'music concert',
  'art fair',
  'street performance',
  'renaissance fair',
  'Christmas market',
  'haunted house',
  'balloon festival',
  'wine and food pairing',
  'barbecue championship',
  'ice cream social',
  'street dance',
  'magic and illusion',
  'film screening',
  'fashion runway',
  'design thinking',
  'interior design',
  'vintage car',
  'motorbike stunt',
  'Formula 1 race',
  'video game expo',
  'anime and manga convention',
  'cosplay competition',
  'board game cafe',
  'pet fashion show',
  'wine tasting and vineyard tour',
  'organic farming',
  'urban gardening',
  'sustainable fashion',
  'food truck festival',
  'charity gala dinner',
  'blood donation campaign',
  'community service',
  'educational field trip',
  'science museum',
  'historical landmark',
  'art gallery opening',
  'dance party',
  'live band performance',
  'karaoke night',
  'theatre play',
  'improv comedy show',
  'murder mystery dinner',
  'trivia night',
  'wine pairing dinner',
  'cooking competition',
  'street food market',
  'beer festival',
  'craft beer tasting',
  'cider making workshop'
      'Model United Nations conference'
      'Hackathon for social good'
      'Science fair'
      'Robotics competition'
      'Chess tournament'
      'Spelling bee'
      'Quiz bowl competition'
      "Debate tournament"
      'Poetry reading'
      'Open mic night'
      'Comedy show'
      'Dance recital'
      'Opera concert'
      'Symphony orchestra performance'
      'Art auction'
      'Sculpture workshop'
      'Pottery making class'
      'Jewelry making workshop'
      'Calligraphy workshop'
      'Origami session'
      'Floral arrangement class'
      'Wine  painting event'
      'DIY home decor workshop'
];
